# django-storages-s3-auth-bug